### ISSUE TITLE
スポンサー様情報公開について

### ISSUE THREAD

**Issue by Taka710** [PyCon-Kyushu/kyushu.pycon.jp#13]
スポンサー情報（ロゴ、url、紹介文書）をオフィシャルサイトに
公開をお願いいたします。

必要な素材は下記においております。
https://drive.google.com/drive/folders/1qOqtognVh85Cv9sLEGEvsWblf_C5Gft_

**Comment by gorogoroyasu** [comment]
対応したのでクローズします。  
追加がある際は再度issue を立ててください！
