### ISSUE TITLE
メイン背景画像

### ISSUE THREAD

**Issue by gorogoroyasu** [PyCon-Kyushu/kyushu.pycon.jp#2]
http://showcase.city.fukuoka.lg.jp/photo/img0456.html
福岡ドーム の画像が、福岡っぽさがあってよいのではないかと思いますー
↑のリンクの画像は、著作権フリーで使えるようです。 (使途は限定されますが)

**Comment by ykHakata** [comment]
@gorogoroyasu 
いいですね~~、飛行機の写真はとくにこだわりがあるわけではないので、変更してもらっていいですよ!!
ヨロシクです!!👌

**Comment by gorogoroyasu** [comment]
試してみたのですが、文字が白で、背景画像の色が明るいので、
タイトルの文字が読みにくくなっちゃいますねー。。。
少し工夫が必要そうです。
