### ISSUE TITLE
タイムテーブル公開

### ISSUE THREAD

**Issue by massyuu** [PyCon-Kyushu/kyushu.pycon.jp#28]
タイムテーブルの公開をお願いします。
（一部調整中の部分もありますが、そのまま「調整中」で出してもらって大丈夫です）
https://pyconjp-fellow.slack.com/archives/C70N9TKC2/p1527686360000407

【タイムテーブルシート】
https://docs.google.com/spreadsheets/d/1kXaE5-O6qIjvx89xABw-2SL9jxOLP6Kis8dlyslvBMI/edit#gid=1043053022

**Comment by ykHakata** [comment]
こちらの件、本日、午後私、対応します!

**Comment by ykHakata** [comment]
反映しましたのでクローズ
