### ISSUE TITLE
株式会社Medy様　ロゴ公開のお願い

### ISSUE THREAD

**Issue by sbf51cf** [PyCon-Kyushu/kyushu.pycon.jp#29]
ブロンズ　株式会社Medyさま、公式サイトへのロゴの表示をお願いします。

https://drive.google.com/drive/folders/1qOqtognVh85Cv9sLEGEvsWblf_C5Gft_

リンク先は
http://www.medy.co.jp/
でお願いします。

**Comment by ykHakata** [comment]
こちら私がやります!

**Comment by ykHakata** [comment]
反映しました!クローズします
